### ISSUE TITLE
Validation model

### ISSUE THREAD

**Issue by andy-sasa** [sdroh1027/DiffusionVID#3]
Thank you for providing such detailed code and tutorial !!
And I also successfully trained on my own dataset.
But when I want to see the results on may validation set some errors occur.

Like this:

Traceback (most recent call last):
  File "train_net.py", line 243, in <module>
    main()
  File "train_net.py", line 239, in main
    run_test(cfg, model, args.distributed, args.motion_specific)
  File "train_net.py", line 137, in run_test
    inference(
  File "/Jyun_an/DiffusionVID/mega_core/engine/inference.py", line 142, in inference
    predictions = compute_on_dataset(model, data_loader, device, bbox_aug, cfg.MODEL.VID.METHOD, inference_timer, cfg.TEST.SEQ_NMS)
  File "/Jyun_an/DiffusionVID/mega_core/engine/inference.py", line 49, in compute_on_dataset
    output = model(images)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 881, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/apex/amp/_initialize.py", line 196, in new_fwd
    output = old_fwd(*applier(args, input_caster),
  File "/Jyun_an/DiffusionVID/mega_core/modeling/detector/diffusion_det.py", line 336, in forward
    return self._forward_test(images["cur"], infos, targets)
  File "/Jyun_an/DiffusionVID/mega_core/modeling/detector/diffusion_det.py", line 521, in _forward_test
    feats_cur.append(torch.cat([self.feats[i][j] for i in range(range_start, range_end)]))
  File "/Jyun_an/DiffusionVID/mega_core/modeling/detector/diffusion_det.py", line 521, in <listcomp>
    feats_cur.append(torch.cat([self.feats[i][j] for i in range(range_start, range_end)]))
IndexError: deque index out of range

And I have no idea how to deal with this.......

Is it a problem with model setting or data reading?

**Comment by andy-sasa** [comment]
I solved! tks~
